/* Generates supabase/migrations/0002_seed_system_exercises.sql from the bundled exercise library
 * so the cloud and the app always ship the same system exercise ids.  Run: npm run seed:sql */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SYSTEM_EXERCISES } from '../src/database/seed/exercises';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[]) => (a.length ? `array[${a.map(q).join(',')}]::text[]` : "'{}'::text[]");

const lines: string[] = [
  '-- GENERATED by scripts/generate-seed-sql.ts - do not edit by hand.',
  '-- System exercise library (globally readable through RLS).',
  'insert into public.exercises (id, user_id, name, aliases, tracking_mode, primary_muscle, equipment, movement_category, is_system, is_unilateral, created_at, updated_at) values',
];
lines.push(
  SYSTEM_EXERCISES.map(
    (e) =>
      `(${q(e.id)}, null, ${q(e.name)}, ${arr(e.aliases)}, ${q(e.tracking_mode)}, ${q(e.primary_muscle)}, ${q(e.equipment)}, ${q(e.movement_category)}, true, ${e.is_unilateral}, '2026-01-01', '2026-01-01')`,
  ).join(',\n') + '\non conflict (id) do update set name = excluded.name, aliases = excluded.aliases, tracking_mode = excluded.tracking_mode,\n  primary_muscle = excluded.primary_muscle, equipment = excluded.equipment, movement_category = excluded.movement_category, is_unilateral = excluded.is_unilateral;',
);
const sec = SYSTEM_EXERCISES.flatMap((e) => e.secondary_muscles.map((m) => `(${q(e.id)}, ${q(m)})`));
lines.push('', 'insert into public.exercise_secondary_muscles (exercise_id, muscle) values', sec.join(',\n') + '\non conflict do nothing;', '');

writeFileSync(join(__dirname, '..', 'supabase', 'migrations', '0002_seed_system_exercises.sql'), lines.join('\n'));
console.log(`Wrote ${SYSTEM_EXERCISES.length} exercises, ${sec.length} secondary-muscle rows.`);
